# Generated by Django 3.2.5 on 2021-09-14 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chain_marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to='chain_marketing_app.selleraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Android App Users',
                'verbose_name_plural': 'Android App Users',
            },
        ),
    ]
