# Generated by Django 3.2.5 on 2021-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivernumber', models.CharField(blank=True, max_length=50, null=True)),
                ('sendername', models.CharField(blank=True, max_length=50, null=True)),
                ('receivername', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'SOS',
                'verbose_name_plural': 'SOSs',
            },
        ),
    ]
