# Generated by Django 3.2.5 on 2021-09-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_data', '0002_sos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKeys',
            fields=[
                ('activation_key', models.CharField(blank=True, default='URJAF33B5398A6D2', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activation Keys',
                'verbose_name_plural': 'Activation Keys',
            },
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='sponser',
        ),
        migrations.AddField(
            model_name='activeuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ActivationKeys'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='free_service_balance',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='paid_service_balance',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sms_user', to='account.useraccount'),
            preserve_default=False,
        ),
    ]
