# Generated by Django 3.2.5 on 2021-09-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0004_auto_20210922_0928'),
        ('app_data', '0003_auto_20210922_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkeys',
            name='allocated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_marketing_app.memberaccount'),
        ),
    ]
