# Generated by Django 3.2.5 on 2021-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_activationkeys_allocated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeys',
            name='activation_key',
            field=models.CharField(blank=True, default='URJAA63E3CFFCB6F', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='free_service_balance',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
