# Generated by Django 3.2.5 on 2021-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_auto_20211104_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeys',
            name='activation_key',
            field=models.CharField(blank=True, default='URJA9F59C3122543', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
