# Generated by Django 3.2.5 on 2021-11-30 17:46

import app_data.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_alter_activationkeys_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activationkeys',
            name='activation_key',
            field=models.CharField(blank=True, default=app_data.models.unique_rand, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='free_service_balance',
            field=models.IntegerField(default=50),
        ),
    ]
