# Generated by Django 3.2.5 on 2021-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0007_auto_20211130_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='free_service_balance',
            field=models.IntegerField(default=25),
        ),
    ]
