# Generated by Django 3.2.5 on 2022-02-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0015_auto_20220213_1225'),
        ('app_data', '0008_alter_activeuser_free_service_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkeys',
            name='allocated_by',
            field=models.ForeignKey(default='URJAD96737', on_delete=django.db.models.deletion.CASCADE, related_name='allocated_by', to='chain_marketing_app.memberaccount'),
        ),
    ]
