# Generated by Django 3.2.5 on 2022-03-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0021_auto_20220222_1414'),
        ('app_data', '0009_activationkeys_allocated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkeys',
            name='allocated_by',
            field=models.ForeignKey(default='URJAB29A', on_delete=django.db.models.deletion.CASCADE, related_name='allocated_by', to='chain_marketing_app.memberaccount'),
        ),
    ]
