# Generated by Django 3.2.5 on 2021-09-14 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Add Product ',
                'verbose_name_plural': 'Add Products ',
            },
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('sponser_id', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_id', models.CharField(blank=True, default='URJA3CA5', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Account',
                'verbose_name_plural': 'Seller Accounts',
            },
        ),
        migrations.CreateModel(
            name='ProductsOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_owned', to='chain_marketing_app.addproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='chain_marketing_app.selleraccount')),
            ],
            options={
                'verbose_name': 'Assign Products ',
                'verbose_name_plural': 'Assign Products ',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payout', to='chain_marketing_app.selleraccount')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payout',
            },
        ),
    ]
