# Generated by Django 3.2.5 on 2021-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0002_alter_selleraccount_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='seller_id',
            field=models.CharField(blank=True, default='URJA99DF', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
