# Generated by Django 3.2.5 on 2021-09-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_data', '0003_auto_20210922_0928'),
        ('chain_marketing_app', '0003_alter_selleraccount_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('sponser_id', models.CharField(blank=True, max_length=50, null=True)),
                ('member_id', models.CharField(blank=True, default='URJA60C9', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('taluka', models.CharField(blank=True, default='Haveli', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_distributer', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Account',
                'verbose_name_plural': 'Member Accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='addproduct',
            options={'verbose_name': 'Add Product', 'verbose_name_plural': 'Add Products'},
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chain_product/'),
        ),
        migrations.CreateModel(
            name='MemberActivationKey',
            fields=[
                ('key', models.CharField(blank=True, default='URJACDA2A3FF7326', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_marketing_app.memberaccount')),
            ],
            options={
                'verbose_name': 'MemberActivationKey',
                'verbose_name_plural': 'MemberActivationKeys',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('points', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='chain_marketing_app.addproduct')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.AlterField(
            model_name='payout',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payout', to='chain_marketing_app.memberaccount'),
        ),
        migrations.AlterField(
            model_name='productsowned',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='chain_marketing_app.memberaccount'),
        ),
        migrations.DeleteModel(
            name='SellerAccount',
        ),
    ]
