# Generated by Django 3.2.5 on 2021-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0004_auto_20210922_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='APK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk', models.FileField(blank=True, null=True, upload_to='apk/')),
            ],
            options={
                'verbose_name': 'APK',
                'verbose_name_plural': 'APK',
            },
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='member_id',
            field=models.CharField(blank=True, default='URJA45B6', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='memberactivationkey',
            name='key',
            field=models.CharField(blank=True, default='URJAA6204DD32A4B', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
