# Generated by Django 3.2.5 on 2021-11-30 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0006_auto_20211130_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecitydistibuter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 0, 5, 1, 752109)),
        ),
        migrations.AlterField(
            model_name='activemember',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 0, 5, 1, 752109)),
        ),
        migrations.AlterField(
            model_name='activeseller',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 0, 5, 1, 752109)),
        ),
        migrations.AlterField(
            model_name='payout',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
