# Generated by Django 3.2.5 on 2021-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0007_auto_20211201_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecitydistibuter',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activemember',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activeseller',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
