# Generated by Django 3.2.5 on 2021-12-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0008_auto_20211201_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='product',
        ),
    ]
