# Generated by Django 3.2.5 on 2021-12-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chain_marketing_app', '0009_remove_bankdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='member',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='member_bankdetails', to='chain_marketing_app.memberaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_bankdetails', to='account.useraccount'),
            preserve_default=False,
        ),
    ]
