# Generated by Django 3.2.5 on 2021-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0010_auto_20211206_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='upi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
