# Generated by Django 3.2.5 on 2021-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0011_bankdetails_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='tds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='tds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
