# Generated by Django 3.2.5 on 2021-12-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0012_auto_20211214_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payout',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
