# Generated by Django 3.2.5 on 2021-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0013_auto_20211218_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
