# Generated by Django 3.2.5 on 2022-02-13 06:55

import chain_marketing_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0014_alter_payout_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subproductsstock',
            options={'verbose_name': 'SubProductsStock', 'verbose_name_plural': 'Sub Products Stocks'},
        ),
        migrations.CreateModel(
            name='SubProductsSale',
            fields=[
                ('Key', models.CharField(blank=True, default=chain_marketing_app.models.unique_rand, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_member_details', to='chain_marketing_app.memberaccount')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_member_details', to='chain_marketing_app.memberaccount')),
            ],
            options={
                'verbose_name': 'SubProducts Sale',
                'verbose_name_plural': 'SubProducts Sale',
            },
        ),
    ]
