# Generated by Django 3.2.5 on 2022-02-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0015_auto_20220213_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('delivered', models.IntegerField(blank=True, null=True)),
                ('undelivered', models.IntegerField(blank=True, null=True)),
                ('generated', models.IntegerField(blank=True, null=True)),
                ('transfer_in', models.IntegerField(blank=True, null=True)),
                ('transfer_out', models.IntegerField(blank=True, null=True)),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_details1', to='chain_marketing_app.memberaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product1', to='chain_marketing_app.addproduct')),
            ],
            options={
                'verbose_name': 'AllProductStock',
                'verbose_name_plural': 'AllProductStocks',
            },
        ),
    ]
