# Generated by Django 3.2.5 on 2022-02-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0016_allproductstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProductStock',
            new_name='AllMembersProductStock',
        ),
        migrations.AlterModelOptions(
            name='allmembersproductstock',
            options={'verbose_name': 'AllMembersProductStock', 'verbose_name_plural': 'AllMembersProductStock'},
        ),
    ]
