# Generated by Django 3.2.5 on 2022-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0017_auto_20220215_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmembersproductstock',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='allmembersproductstock',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
