# Generated by Django 3.2.5 on 2022-02-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0018_auto_20220215_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroducerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('distributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributer1', to='chain_marketing_app.memberaccount')),
                ('introducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introducer_1details', to='chain_marketing_app.memberaccount')),
            ],
            options={
                'verbose_name': 'Introducer Requests',
                'verbose_name_plural': 'Introducer Requests',
            },
        ),
    ]
