# Generated by Django 3.2.5 on 2022-02-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0019_introducerrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducerrequests',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
