# Generated by Django 3.2.5 on 2022-02-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0020_introducerrequests_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='introducerrequests',
            name='active_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='introducerrequests',
            name='pin_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
