# Generated by Django 3.2.5 on 2022-03-11 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0021_auto_20220222_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeseller',
            name='subproduct_bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MemberLevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_marketing_app.memberaccount')),
            ],
            options={
                'verbose_name': 'MemberLevelInfo',
                'verbose_name_plural': 'MemberLevelInfos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
