# Generated by Django 3.2.5 on 2022-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0022_auto_20220311_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='left',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
