# Generated by Django 3.2.5 on 2022-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0023_auto_20220403_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='left_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='rigth_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
