# Generated by Django 3.2.5 on 2022-04-08 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0024_auto_20220403_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberaccount',
            name='left',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='left_points',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='right',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='rigth_points',
        ),
        migrations.CreateModel(
            name='BinaryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('left', models.CharField(blank=True, max_length=255, null=True)),
                ('right', models.CharField(blank=True, max_length=255, null=True)),
                ('left_points', models.IntegerField(blank=True, default=0, null=True)),
                ('right_points', models.IntegerField(blank=True, default=0, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_tree', to='chain_marketing_app.memberaccount')),
            ],
        ),
    ]
