# Generated by Django 3.2.5 on 2022-04-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0025_auto_20220408_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='left',
            field=models.ForeignKey(default=12121, on_delete=django.db.models.deletion.CASCADE, related_name='left_binary_tree', to='chain_marketing_app.memberaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='parent',
            field=models.ForeignKey(default=121221, on_delete=django.db.models.deletion.CASCADE, related_name='parent_binary_tree', to='chain_marketing_app.memberaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='right',
            field=models.ForeignKey(default=1212, on_delete=django.db.models.deletion.CASCADE, related_name='right_binary_tree', to='chain_marketing_app.memberaccount'),
            preserve_default=False,
        ),
    ]
