# Generated by Django 3.2.5 on 2022-04-08 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0026_auto_20220408_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_binary_tree', to='chain_marketing_app.memberaccount'),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_binary_tree', to='chain_marketing_app.memberaccount'),
        ),
    ]
