# Generated by Django 3.2.5 on 2022-04-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0027_auto_20220408_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberaccount',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
