# Generated by Django 3.2.5 on 2022-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0028_auto_20220408_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarytree',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binarytree',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
