# Generated by Django 3.2.5 on 2022-04-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0029_auto_20220409_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytree',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_binary_tree', to='chain_marketing_app.memberaccount'),
        ),
        migrations.AlterField(
            model_name='binarytree',
            name='right_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
