# Generated by Django 3.2.5 on 2022-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0030_auto_20220409_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryPayoutAttrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_pair', models.IntegerField(blank=True, null=True)),
                ('payable_pairs', models.IntegerField(blank=True, null=True)),
                ('one_point_value', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'BinaryPayoutAttrs',
                'verbose_name_plural': 'BinaryPayoutAttrss',
            },
        ),
    ]
