# Generated by Django 3.2.5 on 2022-04-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0031_binarypayoutattrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binarypayoutattrs',
            old_name='one_point_value',
            new_name='one_pair_value',
        ),
    ]
