# Generated by Django 3.2.5 on 2022-05-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0034_auto_20220416_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIsValidSponser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sponser_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('btmember', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binary_tree', to='chain_marketing_app.binarytree')),
            ],
            options={
                'verbose_name': 'MemberIsValidSponser',
                'verbose_name_plural': 'MemberIsValidSponsers',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
