# Generated by Django 3.2.5 on 2022-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_marketing_app', '0035_memberisvalidsponser'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarytree',
            name='position',
            field=models.CharField(default='Right', max_length=255),
        ),
    ]
